#ifndef _USER_CONFIG_H
#define _USER_CONFIG_H
/*
 *   ADD YOUR TARGET LATITUDE AND LONGITUDE IN THE DEFINE.
 *   AS A FLOATING POINT NUMBER REPRESENTING THE COORDINATE IN DEGREES
 *
 *   ADD A NEW LINE WITH "#define DEBUG" (NO QUOTES) TO ENABLE DEBUG MESSAGES
 */

#define TARGET_POSITION [LAT], [LON] // FORMAT [LAT], [LON] AS float OR int32_t

// COMPASS CALIBRATION PARAMETERS
#define COMPASS_CAL_MIN -470, -1083, +837
#define COMPASS_CAL_MAX +79, -495, +946

// DEBUG PRINTER
#define DEBUG
#define PRINTER_BAUD_RATE 115200

#endif